### PR TITLE
Test against PHP 7.4

### PR DESCRIPTION
**Pull request by gmponos**

### CODE REVIEW

**Comment by Halleck45** [comment]
Hi,

I've restart travic-ci job, and there is two errors:

```
1) Test\Hal\Component\Issue\IssuerTest::testICanEnableIssuer
Error: Object of class stdClass could not be converted to string
/home/travis/build/phpmetrics/PhpMetrics/tests/Component/Issuer/IssuerTest.php:22

2) Test\Hal\Component\Issue\IssuerTest::testIssuerDisplayStatements
Error: Object of class stdClass could not be converted to string
/home/travis/build/phpmetrics/PhpMetrics/tests/Component/Issuer/IssuerTest.php:54
```

Can you fix them ?

**Comment by Halleck45** [comment]
Hi,

Please @gmponos, do not hesitate to squash your commits before merging 🙂

**Comment by jeanfrancois-mevia** [comment]
Sorry @gmponos, you've squashed commits. I need glasses :eyeglasses:

**Comment by Halleck45** [comment]
Sorry @gmponos , I need glasses :eyeglasses:

**Pull request merged**
