### PR TITLE
fix calculation of duration

### LINKED ISSUE #179: Wrong Output of estimated duration to read and understand
When generating a report with cli output, an estimated time is calculated which shows how long it would take to read and understand the code.

`321 files have been analyzed. Read and understand these 20404 lines of code will take around 00 hour(s), 01 minute(s) and 38 second(s).`

This is based on a sum of seconds which are printed with `gmdate()`. But this shows up to be faulty, because if you have time > 24 hours (86400 secs) the hour is still 00. using `gmdate()` is the wrong way to calculate a duration.

This works (credits to http://stackoverflow.com/a/3172665/1609286):

```php
<?php
    /**
     * Format time in text
     *
     * @param null|double $v
     * @return string
     */
    private function formatTime($v) {
        return sprintf('%s hour(s), %s minute(s) and %s second(s)'
            , floor($v / 3600)
            , ($v / 60) % 60
            , $v % 60
        );
    }
```

This produces the correct output:

`321 files have been analyzed. Read and understand these 20404 lines of code will take around 24 hour(s), 48 minute(s) and 38 second(s).`

### PR DESCRIPTION
**Pull request by skors**
this fixes #179 and changes calculation of seconds to hours, minutes and seconds

### CODE REVIEW

**Comment by Halleck45** [comment]
Hi,

Well done! Perhaps this is an opportunity to add a test. Can you make the `formatTime()` method public, and add a unit test in `tests/Hal/Application/Formater/Details/CliTest.php` ?

**Comment by skors** [comment]
@Halleck45 i do not think it is the right way just to set the method public and test it. I think it is protected because it is just used internally in the class, so we should test where it is used. Otherwise you producing a harder way to refactor this class in future.

**Comment by skors** [comment]
@Halleck45 

I think testing the terminate Method correctly is the better way. Our goal is to test if some code produces the sum of n seconds in total, the written string should contain the equivalent of its time as string is the defined format. This will test the protected method `formatTime()` better i think. And we could test it with multiple values (negative, zero, positive, faulty values etc).

Nevertheless i will look into it soon. thanks for phpmetrics!

**Comment by skors** [comment]
@Halleck45 please review, i've added a test for checking correct returned duration string

**Comment by Halleck45** [comment]
Excellent ! Thanks a lot !

**Pull request merged**
