### PR TITLE
adding new metric Coc for Characters of Code

### PR DESCRIPTION
**Pull request by halmai**
I added a new metric which is a pretty straightforward one. Maybe it is the most commonly used if we are talking about how complex a file is. It is called Coc which stands for Characters of Code. It is practically the file size in bytes. 

Please merge it to the main branch. Thanks.

### CODE REVIEW

**Comment by Halleck45** [comment]
Hi,

Can you provide some documentation ? What about blank (spaces) chars ?

**Comment by halmai** [comment]
It counts the fie size measured in bytes, that is, a space is one byte, a tab is one byte and the end of line can be one or two bytes, depending on the line ending encoding used. Similarly, UTF-8 characters can be several bytes long. 

Do you need any more information?

**Comment by pavarnos** [comment]
A better name might be "FileSize"?

Just yesterday I wrote a small analyser to parse an entire project counting LOC, file size in bytes, number of files and aggregate these into modules so I could measure the progress of a refactoring (eg i'm 5% finished). Might be handy to have FileSize included as one column in the metrics reports for this purpose: i could then see the quality of each module as well.

**Comment by Halleck45** [comment]
Yes, "FileSize" looks great. @halmai can you change "coc" for "fileSize" in your PR please ?

**Comment by halmai** [comment]
Sure, I will do it shortly, within a couple of days, as soon as I find some time for it.

**Comment by halmai** [comment]
Hi Guys, finally I had some time to make the modifications we discussed above. Sorry for the delay. Do you think it can be merged now?

**Comment by halmai** [comment]
Hi,

thank you for merging it. :)

Cheers,

Csongor

**Pull request merged**
