### PR TITLE
Package metrics

### PR DESCRIPTION
**Pull request by UFOMelkor**
This PR adds package metrics to PhpMetrics.

Packages are recognized by @package/@subpackage annotations in the DocBlock of a class / interface / … or by the namespace (if not annotations are found).

Current status is

 - [x] Add package metrics
   - [x] Number of classes
   - [x] Abstraction / Instability / Distance
   - [x] Incoming and outgoing class dependencies
   - [x] Incoming and outgoing package dependencies
 - [x] Add package violations:
   - [x] Stable Dependencies Principle
   - [x] Stable Abstractions Principle
 - [x] Reporter
   - [x] Html
      - [x] Package metrics
      - [x] AbstractiontInstability diagram
      - [x] Package relations
      - [x] Package violations
   - [x] Cli
   - [x] Violations
 - [x] Add tests
 - [x] Handle traits

Any feedback would be appreciated :blush: 

Some images from a PhpMetrics analysis:
image
image
image

### CODE REVIEW

**Comment by tPl0ch** [comment]
@UFOMelkor What is the status of this PR? We are really interested in your work here, so if I can somehow help you with finishing the implementation ping me.

**Comment by UFOMelkor** [comment]
@tPl0ch Thank you for reminding me of this PR.

There are two questions that need be answered:

 - Do violations about the Stable Abstractions Principle make any sense (and if they do, which distance should be used as limit)?
 - How are traits handled related to packages? I tend to handle them like concrete classes.

Apart from this I hope everything is stable now. You could run an analysis of this branch against your code to check whether errors are thrown or not.

**Comment by Halleck45** [comment]
@UFOMelkor hard work done :+1: 

Can you rebase your PR please ? How can we help you to finish ?

**Comment by UFOMelkor** [comment]
Perhaps you have some thoughts about this two questions …

> - Do violations about the Stable Abstractions Principle make any sense (and if they do, which distance  should be used as limit)?
> - How are traits handled related to packages? I tend to handle them like concrete classes.

**Comment by niconoe-** [comment]
About SAP, I'm documenting on it as I'm not totally aware of this. I'll give you my thoughts later.

About Trait handling, I think treating them like classes is a good option. Don't forget that horizontally extends doesn't exist in PHP and Traits are a kind of solution to that miss. This tend to understand traits usages as horizontal inheritance, like classes would do if PHP allow it.

**Comment by carusogabriel** [comment]
If #329 goes merge, please use `PHPUnit\Framework\TestCase` instead of `PHPUnit_Framework_TestCase`.

**Comment by Mte90** [comment]
any updates for this one?

**Pull request merged**
