### PR TITLE
Test on PHP 7.3

### PR DESCRIPTION
**Pull request by lencse**

### CODE REVIEW

**Comment by hopeseekr** [comment]
Is this project in a semi-abandoned state?

**Comment by Mte90** [comment]
Ping for this pr!

**Comment by hopeseekr** [comment]
I'm legitly thinking about having my corporation officially fork this project. With 1,800 stars and issues and PRs just dangling in the wind for 2+ years, and the last commit being over 10 months ago... Maybe the owner(s) can just make me a maintainer of this project and I'll clean it all up.

**Comment by giovannimesquita** [comment]
Why not just do a fork and improve it?

**Comment by Mte90** [comment]
I don't have time to do a fork and maintain, I think that will be enough that the project maintaner add more people to this repo to do this kind of maintanance.

**Comment by Mte90** [comment]
@UFOMelkor just a ping

**Comment by ecourtial** [comment]
Agree. If someone want to fork this project, I will be happy to help to maintain it.
But the best solution would be definitively to add maintainers @UFOMelkor

**Comment by Halleck45** [comment]
Hi,

thanks all for your interest and efforts !

I'm sad to see PhpMetrics abandonned, and I hope that, in the future, I'll be able to work again on this project.

I can add new maintainers on PhpMetrics. **Who would like to participate and be a maintainer?** @ecourtial @hopeseekr can I add you ?

**Comment by gmponos** [comment]
I would like to be a maintainer of the project...

**Comment by Halleck45** [comment]
Nice @gmponos ! Thanks you

**Comment by ecourtial** [comment]
@Halleck45 Yes you can, please :)

**Comment by Halleck45** [comment]
@ecourtial your Github account looks empty. Do you have another profile ? For security reason (the propagation of malwares via this package) I cannot just add you as maintainer without have informations on you and your implication in Open Source community :)

**Comment by ecourtial** [comment]
@Halleck45 Sure, my personal account (the current one being my professional one) : enrico69

**Pull request merged**
